In [4]:
import numpy as np
print (np.version.version)

1.16.5


In [6]:
a = np.random.random((2,3,5))
print (a)

[[[0.62204014 0.8649637  0.11385464 0.46444231 0.73106722]
  [0.13989112 0.88203857 0.98616741 0.06054316 0.21190758]
  [0.10108994 0.83278644 0.88697504 0.06730669 0.5203713 ]]

 [[0.48784356 0.82209025 0.43648626 0.98206557 0.60965555]
  [0.1762449  0.35723509 0.94063574 0.11926763 0.10341031]
  [0.69517511 0.61173762 0.22969014 0.08530264 0.28712646]]]


In [26]:
b= np.full((5,2,3),1)
print (b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [31]:
a.size

30

In [29]:
b.size

30

In [63]:
f=b.transpose(2,3,5).shape
print (f)

AxisError: axis 3 is out of bounds for array of dimension 3

In [64]:
b.reshape(2,3,5)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [34]:
c=b.reshape(2,3,5)
print (c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [37]:
a+c

array([[[1.62204014, 1.8649637 , 1.11385464, 1.46444231, 1.73106722],
        [1.13989112, 1.88203857, 1.98616741, 1.06054316, 1.21190758],
        [1.10108994, 1.83278644, 1.88697504, 1.06730669, 1.5203713 ]],

       [[1.48784356, 1.82209025, 1.43648626, 1.98206557, 1.60965555],
        [1.1762449 , 1.35723509, 1.94063574, 1.11926763, 1.10341031],
        [1.69517511, 1.61173762, 1.22969014, 1.08530264, 1.28712646]]])